### ISSUE TITLE
Allow a property to be set to a static string

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMetaTags#11]
For most meta tags setting to a property is the right thing. There are some though that the entire wiki should serve the same string. Example is `go:site_name` for [Open Graph protocol](http://ogp.me). It would be nice to be able to set these static strings as well.

**Comment by mwjames** [comment]
> Example is go:site_name for Open Graph protocol. It would be nice to be able to set these static strings as well.

Mmm ... static, in case we want to support this we will probably need something like `egSMTMetaTagsStaticContentDescriptor` to avoid meddling with the definition/definitions of `egSMTMetaTagsContentPropertySelector`

**Comment by JeroenDeDauw** [comment]
I suggest to use `egSemanticMetaTagProperties` and `egSemanticMetaTagStrings` as names. I'm reading the current thing as "long hard to read name that luckily I don't have to remember since it's the only one anyway" :)

**Comment by mwjames** [comment]
Added by #17
