### ISSUE TITLE
Support for Twitter cards

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMetaTags#12]
Not sure if I could just add additional `twitter:card` meta tags, but I see OpenGraph has a special section so thought I would highlight the potential of adding [Twitter Card](https://dev.twitter.com/cards/types/summary) section as well.

**Comment by mwjames** [comment]
Solved with (or added by) #16

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMetaTags/commit/3744b5043de3de24fa9e191a746b0135e5514691

**Comment by JeroenDeDauw** [comment]
Fixed the tag :)

**Comment by thingles** [comment]
This is awesome. Thanks!
