### ISSUE TITLE
Allow to manipulate/override <title>

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMetaTags#14]
This might be a nice feature. Core as such only allows to manipulate via "MediaWiki:Pagetitle"

**Comment by JeroenDeDauw** [comment]
@kghbln Oh no - soon we'll also have a SemanticTitle extension to maintain!

**Comment by mwjames** [comment]
`<title>` would be a hard sell as it is a meta data but not in terms of its technical description encoded by `<meta ...>`.

**Comment by kghbln** [comment]
Well, true. Since there is already a SemanticTitle extension it will probably overdo things. I currently do not know if SemanticTitle actually overrides the page title or just the display title of the page. I guess the latter. I do not think that it is desirable to override the page title in the first place.

Yeah, let's focus on `<meta ...>` here.
