### ISSUE TITLE
Translatewiki support

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticMetaTags#19]
Step 1 done: https://www.mediawiki.org/wiki/Git/New_repositories/Requests

**Comment by JeroenDeDauw** [comment]
@kghbln @mwjames repo created and synced. Not sure if TWN added it yet

**Comment by JeroenDeDauw** [comment]
You also both have owner rights on the thing

**Comment by kghbln** [comment]
> Not sure if TWN added it yet

This is in the pipeline. Nothing to follow up here. By the way SBL and SIL are now receiving translations after an initial hickup.
