### ISSUE TITLE
Meta tags not showing up consistently

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMetaTags#20]
I’m trying to test the meta tags and am seeing that they are not consistently being rendered on the page. I’m using the [Twitter Card Validator](https://cards-dev.twitter.com/validator) and am getting

```
INFO:  Page fetched successfully
INFO:  8 metatags were found
INFO:  twitter:card = summary tag found
WARN:  Not whitelisted
ERROR: Required meta tag missing (twitter:description)
ERROR: Required meta tag missing (twitter:title)
```

My config is:

```
    # Set Semantic Tags configuration
    $GLOBALS['egSMTMetaTagsContentPropertySelector'] = array(
        // Standard meta tags
        'keywords' => 'Has tag',
        'description' => 'Has description',
        'author' => 'Page author',

        // Twitter Cards
        'twitter:title' => 'Has name',
        'twitter:image' => 'Has image URL',
        'twitter:description' => 'Has description',

        // Open Graph protocol supported tags
        'og:title' => 'Has name',
        'og:image' => 'Has image URL',
        'og:description' => 'Has description'
    );

    $GLOBALS['egSMTMetaTagsStaticContentDescriptor'] = array(
        // Static tags
        'twitter:card' => 'summary',
        'twitter:site' => '@WikiApiary',
        'og:site_name' => 'WikiApiary'
    );
```

When I test with curl though, it confirms that only the static meta tags are showing up!

```
➜  w  curl --silent -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30" 'https://wikiapiary.com/wiki/WikiApiary' | grep twitter
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@WikiApiary" />
```

I can also confirm this using Show source in my browser. 

This is what I’m seeing using https://wikiapiary.com/wiki/WikiApiary

1. Hit refresh in page tools and I see all 5 tags, looks perfect!
2. Trigger refresh in browser (browser refresh, not mediawiki) and all 5 meta tags are still there. Great!
3. Hit browser refresh again and only the static ones are present.

If I go to a browser that is not logged in, I can never see the meta tags (except for the static ones).

Wondering if this is somehow related to #9 and the PageOutput thing mentioned there.

**Comment by mwjames** [comment]
Should be solved by https://github.com/SemanticMediaWiki/SemanticMetaTags/blob/master/src/LazySemanticDataFetcher.php#L10

**Comment by thingles** [comment]
Just updated `a84e06e => bbd4781` and they are showing up consistently!

Also my checks using the Twitter Card checker and Facebook open graph validator now pass! Thanks!
