### ISSUE TITLE
Allow fallback properties?

### ISSUE THREAD

**Issue by thingles** [SemanticMediaWiki/SemanticMetaTags#21]
When I first saw the example given in README.md of

```
 'keywords' => 'Has keywords, Has another keyword',
```

I thought that meant it would use Property:Has keywords, and if empty fallback to Property:Has another keyword. Actually the behavior is more like concatenating the two properties, and even leaves the comma in the concatenated output (which seems a little odd, but intentional).

It would be really nice to be able to provide a proper array instead.

```
 'keywords' => ['Has keywords', 'Has another keyword'],
```

And have it use the first item in the array that returns non-null output. 

This may be feature creep and considered beyond scope, but I immediately wanted to use this on WikiApiary for

```
 'keywords' => 'Has description, Has tagline',
```

To use a description if provided and if not a tagline.

**Comment by mwjames** [comment]
> I thought that meant it would use Property:Has keywords, and if empty fallback to Property:Has another keyword. Actually the behavior is more like concatenating the two properties, and even leaves the comma in the concatenated output (which seems a little odd, but intentional).

See comments made on https://github.com/SemanticMediaWiki/SemanticMetaTags/issues/3#issuecomment-75006982.

> It would be really nice to be able to provide a proper array instead.

Simple comma list vs. array list has not been addressed yet.

**Comment by mwjames** [comment]
> Simple comma list vs. array list has not been addressed yet.

Property assignments can now be either `'Foo,Bar'` or `array( 'Foo', 'Bar' )` (added with c376001d10cc).

@thingles If you fetch a new version from git please keep in mind the settings name changes. See https://github.com/SemanticMediaWiki/SemanticMetaTags/issues/3#issuecomment-75006982 / https://github.com/SemanticMediaWiki/SemanticMetaTags/issues/3#issuecomment-75136065 and some input would be appreciated as well.
