### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMetaTags#3]
@SemanticMediaWiki/testers I would appreciate someone is testing this extension before putting a 1.0 tag on it.

To set appropriate property matching [0] and to validate whether a page contains the correct metadata [1].

[0] https://github.com/SemanticMediaWiki/SemanticMetaTags#usage
[1] http://www.geoffhayward.eu/blog/you-can-validate-open-graph-metadata

**Comment by JeroenDeDauw** [comment]
Wow, this must be the greatest extension ever. It has only 56 real lines of production code! That makes it roughly 100 times better than Cargo right?

![phploc](https://cloud.githubusercontent.com/assets/146040/6241077/0efa3c3c-b718-11e4-88b2-62aeec710795.jpg)

The line count and class count are kinda funny. If you don't know classes only referenced are also counted, it's rather

![look-at-this-guy](https://cloud.githubusercontent.com/assets/146040/6241138/a612f82a-b718-11e4-96d0-d0408f7d3996.gif)

Anyway, you can haz #4 and #5

**Comment by kghbln** [comment]
If have just tested the regular meta tags with the following setting on my instance:

```php
$egSMTMetaTagsContentPropertySelector = array(
        'keywords' => 'Keywords',
        'description' => 'Description',
        'author' => 'Author'
        );
```
Works cool for all of them an proved that one could even invent tags. Have not tested the OpenGraph stuff from Facebook though.

**Comment by thingles** [comment]
I’m trying to set the author meta tag to the SESP defined 'Page author' property that that doesn't seem to want to work.

**Comment by thingles** [comment]
@mwjames this is a great extension — thank you for putting it together. All the other extensions that do meta tags are too scary to use, and this one ties into the right data.

I have WikiApiary running this with the following config:

```
$GLOBALS['egSMTMetaTagsContentPropertySelector'] = array(
        // Standard meta tags
        'keywords' => 'Has tag',
        'description' => 'Has description, Has tagline',
        'author' => 'Page author',

        // Open Graph protocol supported tags
        'og:title' => 'Has name',
        'og:image' => 'Has image URL',
        'og:url' => 'Has URL',
        'og:description' => 'Has description, Has tagline'
);
```

I found two issues at #9 and #10.

**Comment by mwjames** [comment]
> I’m trying to set the author meta tag to the SESP defined 'Page author' property that that doesn't seem to want to work. 

As for the SESP issue, see https://github.com/SemanticMediaWiki/SemanticMetaTags/issues/9#issuecomment-74874868

**Comment by mwjames** [comment]
> Works cool for all of them an proved that one could even invent tags.

This is made by design (also one doesn't have to validate the tags since it is up to the user to ensure the correctness of its input but of course things like `KeWOrds` will be normalized and become `keywords`).

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMetaTags/issues/11#issuecomment-74913191

> I suggest to use egSemanticMetaTagProperties and egSemanticMetaTagStrings as names. I'm reading 

Any preference on the settings naming?

**Comment by kghbln** [comment]
> This is made by design ...

:+1: 

> Any preference on the settings naming?

For SMW, SF and SESP were are configuration parameters like `$smwgQEqualitySupport`, `$sfg24HourTimeX` and `$sespSpecialProperties` so to have it more consistently `$smtgProperties`/ `$egsmtProperties` and `$smtgStrings`/`$egsmtStrings` might be an idea. This will fit better to `egSMTMetaTagsContentPropertySelector` which could still be tweaked at this point to e.g. `$smtgContentPropertySelector`/`$egsmtContentPropertySelector`

**Comment by mwjames** [comment]
> which could still be tweaked at this point to e.g. $smtgContentPropertySelector/$egsmtContentPropertySelector

You can just change the setting in [0] together with the `README.md` once an agreement is reached on the naming (all internal references are independent from the external naming scheme).

[0] https://github.com/SemanticMediaWiki/SemanticMetaTags/blob/master/SemanticMetaTags.php#L44

**Comment by mwjames** [comment]
#17 adds the static content descriptor therefore making it the deluxe meta setter.

**Comment by thingles** [comment]
FIRST!

https://wikiapiary.com/wiki/Extension:Semantic_Meta_Tags

**Comment by JeroenDeDauw** [comment]
> FIRST!

![thumbs-up](https://cloud.githubusercontent.com/assets/146040/6260500/0a8b5cb2-b7e0-11e4-8242-12afb8ee17f2.gif)

**Comment by mwjames** [comment]
> This will fit better to egSMTMetaTagsContentPropertySelector which could still be tweaked at this point to e.g. $smtgContentPropertySelector/$egsmtContentPropertySelector

#22 includes some renaming:

- Renamed `egSMTMetaTagsContentPropertySelector` to `smtgTagsContentPropertySelector`
- Renamed `egSMTMetaTagsStaticContentDescriptor` to `smtgTagsStaticContentDescriptor`
- Added `smtgFallbackUseForMultipleProperties` which if set `true` will only return content for the first available property that has values on the assigned tag
- Added `smtgTagsBlacklist` and contains a list of tags that are disabled by default (e.g. `robots` etc.)

@kghbln I leave the fine tuning in terms of re-naming into your skilled hands

**Comment by kghbln** [comment]
I do not think that the configuration settings need further re-naming after your #22 Looks cool to me. Still need someone to test the og and twitter stuff.

**Comment by mwjames** [comment]
> Still need someone to test the og and twitter stuff.

Citing https://github.com/SemanticMediaWiki/SemanticMetaTags/issues/20#issuecomment-74993513, "Also my checks using the Twitter Card checker and Facebook open graph validator now pass!"

**Comment by kghbln** [comment]
:+1:

**Comment by JeroenDeDauw** [comment]
> smtgTagsContentPropertySelector smtgTagsStaticContentDescriptor

I still think these names are not very clear to end users. "Content Property Selector"??? "Static Content Descriptor"??

**Comment by JeroenDeDauw** [comment]
> smtgTagsContentPropertySelector smtgTagsStaticContentDescriptor

I still think these names are not very clear to end users. "Content Property Selector"??? "Static Content Descriptor"??

**Comment by JeroenDeDauw** [comment]
> smtgTagsContentPropertySelector smtgTagsStaticContentDescriptor

I still think these names are not very clear to end users. "Content Property Selector"??? "Static Content Descriptor"??

**Comment by JeroenDeDauw** [comment]
I still suggest to use `egSemanticMetaTagProperties` and `egSemanticMetaTagStrings` as names. Or `smtgTagProperties` and `smtgTagStrings`.

**Comment by JeroenDeDauw** [comment]
@mwjames any blockers for the 1.0 rel left?

**Comment by thingles** [comment]
> I still suggest to use egSemanticMetaTagProperties and egSemanticMetaTagStrings as names. Or smtgTagProperties and smtgTagStrings.

I would vote for `smtgTagProperties` and `smtgTagStrings` as they match the pattern that Semantic MediaWiki uses (e.g., `smwgNamespacesWithSemanticLinks`).

**Comment by thingles** [comment]
> any blockers for the 1.0 rel left?

I just pulled the newest code and updated my config (thank you @mwjames for #21). All looks good.

This is my config on WikiApiary.

```
    # Set Semantic Tags configuration
    $GLOBALS['smtgFallbackUseForMultipleProperties'] = true;
    $GLOBALS['smtgTagsContentPropertySelector'] = array(
        // Standard meta tags
        'keywords' => 'Has tag',
        'description' => array('Has description', 'Has tagline'),
        'author' => 'Page author',

        // Twitter Cards
        'twitter:title' => 'Has name',
        'twitter:image' => 'Has image URL',
        'twitter:description' => array('Has description', 'Has tagline'),

        // Open Graph protocol supported tags
        'og:title' => 'Has name',
        'og:image' => 'Has image URL',
        'og:description' => array('Has description', 'Has tagline'),
    );

    $GLOBALS['smtgTagsStaticContentDescriptor'] = array(
        // Static tags
        'twitter:card' => 'summary',
        'twitter:site' => '@WikiApiary',
        'og:site_name' => 'WikiApiary'
    );
```

**Comment by thingles** [comment]
I think it would be good to reference #9 in the README before release. I created #28 with verbiage for that.

**Comment by mwjames** [comment]
>  any blockers for the 1.0 rel left?

No

**Comment by JeroenDeDauw** [comment]
+1 to the names suggested by @thingles. @mwjames you fine with those? I suggest to change that and then rel.

**Comment by mwjames** [comment]
> you fine with those?

No objections.

**Comment by JeroenDeDauw** [comment]
I guess you want me to make the PR with the rename?

**Comment by kghbln** [comment]
I could do it if it is just renaming the parameters. Guess this should actually be it.

**Comment by kghbln** [comment]
Done with help and pull request https://github.com/SemanticMediaWiki/SemanticMetaTags/pull/29 Sometimes one may complicate things more than necessary. Talking about me here. ;)

**Comment by kghbln** [comment]
Before the release we need another sync with WMF repo to get in the translations.

**Comment by JeroenDeDauw** [comment]
You can haz translations 315f94a6d6b917ca1115b057e5951f0977e5c632

**Comment by kghbln** [comment]
Cool. Just expanded the RELEASE-NOTES. I believe @mwjames should do the honours of bumping the version and tagging the release. Thank you for this great extension!

**Comment by thingles** [comment]
@mwjames just to echo what @kghbln said — every other extension that I researched to do meta tags was janky and made me nervous to install. This clean, test-covered extension is a huge win. The fact that it ties into Semantic MediaWiki properties is all bonus points on top!

**Comment by JeroenDeDauw** [comment]
**Asking James to make a release**

![frisbee](https://cloud.githubusercontent.com/assets/146040/6425973/02f58b08-bf42-11e4-9d5c-a5b84f65920a.gif)

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticMetaTags/releases/tag/1.0.0

**Comment by JeroenDeDauw** [comment]
That image also applies to James responding to my very valuable review input :)

@mwjames shall I send a mail to the SMW user and MW admin lists?

**Comment by mwjames** [comment]
:+1:

**Comment by mwjames** [comment]
@thingles Please remember to change your settings naming that was introduced by #29.
