### ISSUE TITLE
name vs. property

### ISSUE THREAD

**Issue by Protonotarios** [SemanticMediaWiki/SemanticMetaTags#33]
### Setup and configuration

- SMW version: 2.4.6
- SMT version: 1.3.0
- MW version: 1.28.0
- MySQL: 5.6.36-82.0

### Issue

Facebook debugger returns: 
> Share App ID Missing
> The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.

even though `fb:app_id` is declared in my configuration:
```php
$GLOBALS['smtgTagsProperties'] = array(

	// Standard meta tags
	'keywords'            => array('Has meta tag keywords', 'Has another keyword'),
	'description'         => 'Has meta tag description',
	'author'              => 'Has meta tag author',

	// Summary card tag
	'twitter:title'       => 'Has meta tag title',
	'twitter:description' => 'Has meta tag description',
	'twitter:image'       => 'Has meta tag image',

	// Open Graph protocol supported tag
	'og:title'            => 'Has meta tag title',
	'og:description'      => 'Has meta tag description',
	'og:type'             => 'Has meta tag type',
	'og:image'            => 'Has meta tag image'
);
$GLOBALS['smtgTagsStrings'] = array(

	// Static content tag
	'fb:app_id' => '1234567890'
);
```
but it renders as:
```html
<meta charset="UTF-8" />
<meta name="ResourceLoaderDynamicStyles" content="" />
<meta name="generator" content="MediaWiki 1.28.0" />
<meta name="description" content="XXXXXXXX" />
<meta name="twitter:title" content="XXXXXXXX" />
<meta name="twitter:description" content="XXXXXXXX" />
<meta name="twitter:image" content="http://XXXXXXXX.jpg" />
<meta name="fb:app_id" content="1234567890" />
<meta property="og:title" content="XXXXXXXX" />
<meta property="og:description" content="XXXXXXXX" />
<meta property="og:type" content="XXXXXXXX" />
<meta property="og:image" content="http://XXXXXXXX.jpg" />
```

So it seems that `fb:app_id` renders as `name="fb:app_id"` when it should be `property="fb:app_id"`.

Why do some tags render as names and others as properties? For example, my Twitter and Facebook tags are assigned to the exact same semantic properties so I can't understand why they render differently. Is there a way to control whether they render as names or properties?

Thanks! This extension is awesome!!!!

**Comment by kghbln** [comment]
To me it looks like that SMT detects the prefixes of the tags and either adds it to `name` or `property`, e.g. "og" goes to `property` and "twitter" and the rest to `name`.

Perhaps something like `$smtgTagsPropertyStrings` additionally to `$smtgTagsStrings` will help to explicitly add tags to `property` if an automated logic does not fit best.

**Comment by kghbln** [comment]
To me it looks like that SMT detects the prefixes of the tags and either adds it to `name` or `property`, e.g. "og" goes to `property` and "twitter" and the rest to `name`.

Perhaps something like `$smtgTagsPropertyStrings` additionally to `$smtgTagsStrings` will help to explicitly add tags to `property` if an automated logic does not fit best.

**Comment by Protonotarios** [comment]
And maybe an additional properties variable is needed too. Because there are [other Facebook values](http://ogp.me/) that don't start with `og:`  such as `music:`, `video:`, etc. which render as `name` and debugger doesn't seem to recognise them as values.

**Comment by kghbln** [comment]
It is debatable whether this is a bug or an enhancement. I guess it does not really matter how this is labeled exactly.

Anyways, thanks for reporting and making aware of this extra fb-stuff.

**Comment by mwjames** [comment]
Hi,

> Why do some tags render as names and others as properties? For example, my

As noted in [0], only where `og:` is used we assume to use the
`property` attribute any other identifier is handled as `meta name
...`.

Maybe a better way to handle this situation is to map it:

$GLOBALS['smtgMetaPropertyDeclaration'] = array(
  'og:'
   ...
);

and allow to cover other related cases.

[0] https://github.com/SemanticMediaWiki/SemanticMetaTags/blob/master/src/OutputPageHtmlTagsInserter.php#L91-L103

Cheers

**Comment by kghbln** [comment]
> Maybe a better way to handle this situation is to map it:

This could indeed make things easier since this would allow for more flexibility on an earlier configuration level. Also it will be easier to extend via a default setting provided by the extension.

**Comment by kghbln** [comment]
@Protonotarios It will be nice if you could test the related enhancement. I could then do the 1.4.0 release if @mwjames has no objections.
