### ISSUE TITLE
Make `$smtgTagsProperties` take precedence over `$smtgTagsStrings`

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticMetaTags#60]
## Issue

Currently settings for `$smtgTagsProperties` and `$smtgTagsStrings` are both considered and added to the head for the same meta element, e.g. setting

```php
$smtgTagsProperties = [
	'description' => 'Meta-Element description'
];
```
together with an annotation set on a page and
```php
$smtgTagsStrings = [
	'description' => 'My awesome wiki'
];
```
will result into two meta elements for "description" in the head on the same page.

However there are many wikis out there which do not use templates on all their content pages. Thus they need to set `$smtgTagsStrings` to get e.g. a description out to the head of every page. This however removes the possibility to add page specific and more tailored descriptions via templates were possible.

Thus it will be great if a value passed via `$smtgTagsProperties` takes precedence over values set via `$smtgTagsStrings` for the very same meta element.

**Comment by alex-mashin** [comment]
@kghbln, could you please try to reach your goal with adding a closure to `$smtgTagsProperties` returning a fallback constat string and setting `$smtgTagsPropertyFallbackUsage = true`?

**Comment by kghbln** [comment]
Now on board with https://github.com/SemanticMediaWiki/SemanticMetaTags/pull/62
