### ISSUE TITLE
Ask for a example page that is using Semantic Meta Tags

### ISSUE THREAD

**Issue by CALLMELARE** [SemanticMediaWiki/SemanticMetaTags#70]
### Setup and configuration

- SMW version:3.2.3
- SMT version:3.0.0
- MW version:1.35.4
- DB (MySQL etc.):MySQL 

### Issue

I'm trying to create a page of Semantic Meta Tags, I recognize that there was an example on Semantic MediaWiki Sandbox. However, this site is unavailable right now which says:

> "sandbox.semantic-mediawiki.org" is currently not available and should be back in the first quarter of 2022.

I would be appreciate it if you can provide an example for me. Here is my email: yunfei@tju.edu.cn
Thank you all the same.

**Comment by kghbln** [comment]
It is back again. On the following page you can see the configuration the extension uses: https://sandbox.semantic-mediawiki.net/wiki/SMW_Sandbox:Setup_information
